### ISSUE TITLE
Hi, I'm newbie to pfsense and have some questions

### ISSUE THREAD

**Issue by n0th1nt0lOOz** [sergiotocalini/zaovpn#2]
Is deploy_zabbix.sh executed on pfsense server? and the '0.0.0.0' replace with the pfsense's IP or zabbix? And zaovpn.sh is placed on zabbix server?
Looking forward to hearing from you
Thanks

**Comment by sergiotocalini** [comment]
Hi @tientmse62290 
Thanks for your message.
It should work fine on pfsense too using the deploy_zabbix.sh. The zaovpn.sh has to be placed on the pfsense server with the zabbix_agent.
Best,
Sergio
