### ISSUE TITLE
Error when zabbix server request data

### ISSUE THREAD

**Issue by tydoo** [sergiotocalini/zaovpn#4]
Hello,

I install with the zabbix deploi script on the openvpn server.

I restart zabbix agent on openvpn server, and i add the xml on the zabbix server.

**When all is started, i have this errror :** 
![image](https://user-images.githubusercontent.com/50534204/112111630-bf03bf00-8bb4-11eb-9abd-ea409d578bfb.png)

**Error on the red tip :** 
![image](https://user-images.githubusercontent.com/50534204/112111761-ef4b5d80-8bb4-11eb-8f13-9931e8c61b56.png)

**Error on the "[OpenVPN] Service: Listening" element test :** 
![image](https://user-images.githubusercontent.com/50534204/112111839-0722e180-8bb5-11eb-80db-cb5bc8c38f08.png)

**Comment by sergiotocalini** [comment]
Hi @tydoo!

This issue is related with your sudo configuration, please ensure that the monitoring user has the right permissions.
I've just added some information in the README.md file.

Best,
Sergio
